/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/data-table': RouteRecordInfo<'/data-table', '/data-table', Record<never, never>, Record<never, never>>,
    '/form-validation': RouteRecordInfo<'/form-validation', '/form-validation', Record<never, never>, Record<never, never>>,
    '/list-pagination': RouteRecordInfo<'/list-pagination', '/list-pagination', Record<never, never>, Record<never, never>>,
  }
}
