/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/animation-end': RouteRecordInfo<'/animation-end', '/animation-end', Record<never, never>, Record<never, never>>,
    '/data-table': RouteRecordInfo<'/data-table', '/data-table', Record<never, never>, Record<never, never>>,
    '/data-table-external-sort-and-pagination': RouteRecordInfo<'/data-table-external-sort-and-pagination', '/data-table-external-sort-and-pagination', Record<never, never>, Record<never, never>>,
    '/data-table-with-use-fetch': RouteRecordInfo<'/data-table-with-use-fetch', '/data-table-with-use-fetch', Record<never, never>, Record<never, never>>,
    '/form-validation': RouteRecordInfo<'/form-validation', '/form-validation', Record<never, never>, Record<never, never>>,
    '/lazy-loading-state': RouteRecordInfo<'/lazy-loading-state', '/lazy-loading-state', Record<never, never>, Record<never, never>>,
    '/list-fetch-more': RouteRecordInfo<'/list-fetch-more', '/list-fetch-more', Record<never, never>, Record<never, never>>,
    '/list-pagination': RouteRecordInfo<'/list-pagination', '/list-pagination', Record<never, never>, Record<never, never>>,
    '/list-sort': RouteRecordInfo<'/list-sort', '/list-sort', Record<never, never>, Record<never, never>>,
    '/scroll-to': RouteRecordInfo<'/scroll-to', '/scroll-to', Record<never, never>, Record<never, never>>,
    '/scroll-to-promise': RouteRecordInfo<'/scroll-to-promise', '/scroll-to-promise', Record<never, never>, Record<never, never>>,
  }
}
